// Auto-generated ASCII representation of SAE India logo

export const LOGO_COLS = 76;
export const LOGO_ROWS = 42;

export const ASCII_LOGO: string[] = [
  "                                 ..:::::..                                  ",
  "                         :-+*#%@@@@@@@@@@@@@%#*=-.                          ",
  "                    .-+%@@@@@@@@@@@%%%%@@@@@@@@@@@%*=:                      ",
  "                 .=#@@@@@@@@@@@@@@%@@@@%%@@@@@@@@@@@@@%*-.                  ",
  "               =%@@@@@@@@@@@@@@@@#@@@@@@%%@@@@@@@@@@@@@@@%*:                ",
  "            .+@@@@@@@@@@@@@@@@@@%@@@@@@@@#@@@@@@@@@@@@@@@@@@#-              ",
  "          .*@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@%@@@@@@@@@@@@@@@@@@@#-            ",
  "         +@@@%%%%@@@@@@@@@@@@@@%@@@@@@@@@@%@@@@@@@@@@@@@@%%%%%@@#:          ",
  "       :%@@@#@@@@@@%%%@@@@@@@@@%@@@@@@@@@%###%@@@@@@@%%%@@@@@%%@@@= .       ",
  "      =@@@@@%@@@@@@@@@%%%###%@%%@@@@@@@@@#*#**@@@@%%@@@@@@@@@@%@@@@#..      ",
  "     *@@@@@@%@@@@@@@@@@@*****@%@@@@@@@@@@%###%@%%@@@@@@@@@@@@#@@@@@@%..     ",
  "    *@@@@@@@@#@@@@@@@@@@%###%%%@@@@@@@@@@@@@%%%@@@@@@@@@@@@@%%@@@@@@@@:.    ",
  "   *@@@@@@@@@@%@@@@@@@@@@@@@@%****++=+++*+***@@@@@@@@@@@@@@%%@@@@@@@@@@..   ",
  "  -@@@@@@@@@@@@%@@@@@@@@@@@#*+++**######@**+++*%@@@@@@@@@@%%@@@@@@@@@@@% .  ",
  "  @@@@@@@@@@@@@@#@@@@@@@@*+=**%%@@@@%*@@@@@***+++%@@@@@####@@@@@@@@@@@@@+   ",
  " *@@@@@@@@@@@@@@@%%@@@@%+=*%%@@@@#*#**#**@@@@@***+*@@@%****%@@@@@@@@@@@@@:  ",
  ".@@@@@@@@@@@@@%#%@%%@@#=##%@@@@@@+:==-*+-@@@@@@%*#*=@@%###%@@@@@@@@@@@@@@*  ",
  "=@@@@@@@@@@@@#****%%%*=**@@@@@@@@@=--:==#@@@@@@@@*@+=%#%%%@@@@@@@@@@@@@@@@. ",
  "#@@@@@@@%%%%%%#*##@@@-#+@@@@@@@@@@%#+=+%@@@@@@@@@@*#=*@@@@@@@%%%%%@@@@@@@@- ",
  "@@@@%%%%@@@@@@@@@@@@*+*#@@@@@@@@@@%%%%%%%@@@@@@@@@%*#=@@@@@@@@@@@@@%%%@@@@+ ",
  "@@@%@@@@@@@@@@@@@@@@+*+%@@@@@%%%%@@%@%%%%%%%%@@@@@@+#=@@@@@@@@@@@@@@@@@@@@* ",
  "@@+:::::::::::::::::.#%@@@@@@*+**+*@+:--*****@@@@@@%@-:::::::::::::::::.%@* ",
  "@@=                  #@@@@@@@+=+***-.*:.*##*%@@@@@@@@.                  %@* ",
  "#@@@@%#*+=:          =@@@@@@@**#*-..=+..*##*%@@@@@@@%           =+**#%@@@@= ",
  "=@@@@@@@@@@           #@@@@@@#**+-+@@%==****#@@@@@@@:          +@@@@@@@@@@: ",
  " @@@@@@@@@@+           %@@*#@**@%#@+##*%@+%@%+*@@@@-           @@@@@@@@@@%  ",
  " *@@@@@@@@@*            *@=*@=#+=*@-%@=+@-%%=#=+@@-           :@@@@@@@@@@=  ",
  "  @@@@@@@*:              -*%@#@@*%@####@@*@#%@@*+               =%@@@@@@@   ",
  "  =@@@@+.                  -#@@@@@@@@@@@@@@@@%+.                  -#@@@@-   ",
  "   *@%                        -+#%@@@@@@%#*=.                       +@@+    ",
  "    #@*        ::                   ...                   :.       -@@*     ",
  "     #@#  :-*#@@@*.                                     =@@@%*=:. -@@*      ",
  "      +@@@@@@@@@@@@*                                  -%@@@@@@@@@%@@+       ",
  "       -@@@@@@@@@@@*                                  :@@@@@@@@@@@@-        ",
  "        .#@@@@@@@@@                                    =@@@@@@@@@#.         ",
  "          -%@@@@@@-       .##*=-.         :-+*%=        #@@@@@@%-           ",
  "            -%@@@*       =@@@@@@@.       *@@@@@@#.      .@@@@%=             ",
  "              -#@@*-   .#@@@@@@@@=       %@@@@@@@@=   .=#@@#-               ",
  "                .+%@@#+@@@@@@@@@@#      :@@@@@@@@@@#+%@@%+.                 ",
  "                   .=#@@@@@@@@@@@@      +@@@@@@@@@@@@#=.                    ",
  "                       .=*#@@@@@@@%*****@@@@@@@@%*=:                        ",
  "                            .:-+**#%%%%%#**+=-.                             ",
];

export const ASCII_COLORS: string[] = [
  "                                DDDDDDDDDD                                  ",
  "                         DMSSWWWWWWWWWWWWWWWWSSMMD                          ",
  "                    DMSWWWWWWWWWWWWWWWWWWWWWWWWWWWWSMD                      ",
  "                 DMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSMD                  ",
  "               MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSD                ",
  "            DSWWWWWWWWWWWWWWWWWWWWWWWWWWWGWWWWWWWWWWWWWWWWWWSM              ",
  "          DSWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM            ",
  "         MWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWSD          ",
  "       DWWWWGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWGGGWWWWWWWWWWWWWWWWWWWWWM D       ",
  "      MWWWWWWWWWWWWWWWWWWGGGWWWWWWWWWWWWWGGGGGWWWWWWWWWWWWWWWWWWWWWSDD      ",
  "     SWWWWWWWWWWWWWWWWWWGGGGGWWWWWWWWWWWWWGGGWWWWWWWWWWWWWWWWWWWWWWWWDD     ",
  "    SWWWWWWWWGWWWWWWWWWWWGGGGWGWWWWWWWWWWWWWGWWWWWWWWWWWWWWWWWWWWWWWWWDD    ",
  "   SWWWWWWWWWWWWWWWWWWWWWWWWWWGSSSSSMSSSSSSGGWWWWWWWWWWWWWWWWWWWWWWWWWWDD   ",
  "  MWWWWWWWWWWWWWWWWWWWWWWWWSSMSSSSSSSSWSWSSSSSSWWWWWWWWWWWWWWWWWWWWWWWWW D  ",
  "  WWWWWWWWWWWWWWWWWWWWWWWSSMSSWWWWWWWSWWWWWSSSSSSWWWWWWGGGGWWWWWWWWWWWWWS   ",
  " SWWWWWWWWWWWWWWWWWWWWWWMMSWWWWWWWGGGSGGGWWWWWSSSSSWWWGGGGGWWWWWWWWWWWWWWD  ",
  "DWWWWWWWWWWWWWWGGWWWWWSMWWWWWWWWWSMMMMSMMWWWWWWWSSSMWWWGGGWWWWWWWWWWWWWWWS  ",
  "MWWWWWWWWWWWWGGGGGWWGGMSSWWWWWWWWWMMMDMMSWWWWWWWWSWSMWGWWWWWWWWWWWWWWWWWWWD ",
  "SWWWWWWWWWWWWGGGGGWWWMSSWWWWWWWWWWWSSMSWWWWWWWWWWWSSMSWWWWWWWWWWWWWWWWWWWWM ",
  "WWWWWWWWWWWWWWWWWWWWSSSSWWWWWWWWWWWWWGWWWWWWWWWWWWWSSMWWWWWWWWWWWWWWWWWWWWS ",
  "WWWWWWWWWWWWWWWWWWWWMSSWWWWWWWWWWWWWWWWWWWWWWWWWWWWSWMWWWWWWWWWWWWWWWWWWWWS ",
  "WWMDMDDDDDDDDDDDDDDDDSWWWWWWWSSSSSSWSDMMSSSSSWWWWWWWWMDDDDDDDDDDDDDDDDDDWWS ",
  "WWM                  WWWWWWWWSMSSSSMDSDDSSSSWWWWWWWWWD                  WWS ",
  "SWWWWWSSSMD          MWWWWWWWSSSSMDDMSDDSSSSWWWWWWWWW           MMSSWWWWWWM ",
  "MWWWWWWWWWW           WWWWWWWSSSSMSWWWMMSSSSSWWWWWWWD          MWWWWWWWWWWD ",
  "DWWWWWWWWWWS           WWWSSWSSWWWWSSWSWWSWWWSSWWWWM          DWWWWWWWWWWW  ",
  " SWWWWWWWWWS            SWMSWMWSMSWMWWMSWMWWMSMSWWM           DWWWWWWWWWWM  ",
  "  WWWWWWWSD              MSWWSWWSWWSSSWWWSWSWWWSM               MWWWWWWWW   ",
  "  MWWWWSD                  MSWWWWWWWWWWWWWWWWWMD                  MWWWWWM   ",
  "   SWWD                       MSSWWWWWWWWWSMD                       SWWS    ",
  "    SWS        DD                  DDDD                  DDD       MWWS     ",
  "     SWS  DMSWWWWSD                                     MWWWWSMMD MWWS      ",
  "      SWWWWWWWWWWWWS                                  MWWWWWWWWWWWWWS       ",
  "       MWWWWWWWWWWWS                                  DWWWWWWWWWWWWM        ",
  "        DSWWWWWWWWW                                    MWWWWWWWWWSD         ",
  "          MWWWWWWWM       DSWSMMD         DMSSWM        WWWWWWWWM           ",
  "            MWWWWS       MWWWWWWWD       SWWWWWWSD      DWWWWWM             ",
  "              MSWWSM   DSWWWWWWWWM       WWWWWWWWWM   DMWWWSM               ",
  "                DMWWWSSWWWWWWWWWWS      DWWWWWWWWWWSSWWWWSD                 ",
  "                   DMSWWWWWWWWWWWW      SWWWWWWWWWWWWWMD                    ",
  "                       DMSWWWWWWWWWSSSSSWWWWWWWWWSMD                        ",
  "                            DDMMSSWWWWWWSSSSMMD                             ",
];
